### ISSUE TITLE
unable to run sample project

### ISSUE THREAD

**Issue by kilinc89** [Shopify/checkout-sheet-kit-react-native#61]
I could not achieve to run the sample project
```
`error: Error: Unable to resolve module @shopify/checkout-sheet-kit from /Users/mac/Desktop/checkout-sheet-kit-react-native/sample/src/App.tsx: @shopify/checkout-sheet-kit could not be found within the project or in these directories:
  node_modules
  ../node_modules
  ../../../node_modules
  38 |   ShopifyCheckoutSheetProvider,
  39 |   useShopifyCheckoutSheet,
> 40 | } from '@shopify/checkout-sheet-kit';`
```
![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-01 at 20 44 20](https://github.com/Shopify/checkout-sheet-kit-react-native/assets/73741244/e77e9045-d4f5-46a7-8eb4-3d78f643fd14)

**Comment by markmur** [comment]
Hey @kilinc89,

Try running the following commands:

#### Install NPM dependencies

```sh
yarn
```

#### Install Cocoapods

```sh
yarn pod-install sample/ios
```

#### Build the local module

```sh
yarn module build
```

#### Update the dotenv file

Replace the details in the `sample/.env.example` file and rename it to `sample/.env`

```
# Storefront Details
STOREFRONT_DOMAIN="YOUR_STORE.myshopify.com"
STOREFRONT_ACCESS_TOKEN="YOUR_PUBLIC_STOREFRONT_ACCESS_TOKEN"
```

#### Start the sample app

```sh
yarn sample start
```
