### ISSUE TITLE
Would it be possible to retrieve the order ID on "completed" listener callback ?

### ISSUE THREAD

**Issue by anthlasserre** [Shopify/checkout-sheet-kit-react-native#63]
Hey guys 👋🏼 

Currently, the success callback does not return anything. I would like to display an order summary to the user to enhance the post-purchase experience.

```typescript
const successListener = shopifyCheckout.addEventListener("completed", (data) => {
  const orderId = data?.orderId;
  // Do some logic
});
```

Do you think this is faisable ?

**Comment by markmur** [comment]
Hey @anthlasserre,

Improvements to the completed event are [coming soon](https://github.com/Shopify/checkout-sheet-kit-swift/pull/128) to Swift and Android - at which point we'll roll it out for React Native too.

In the meantime, you can get the order ID from the `checkout_completed` "pixel" event:

```
const listener = shopifyCheckout.addEventListener('pixel', event => {
      let orderId: string | undefined;

      if (event?.type === 'STANDARD' && event?.name === 'checkout_completed') {
        orderId = event.data?.checkout?.order?.id;
      }
});
```

**Comment by anthlasserre** [comment]
@markmur Wonderful. Thanks for your quick answer.
