### ISSUE TITLE
Is this checkout SDK will still use a WebView on the long-term ?

### ISSUE THREAD

**Issue by anthlasserre** [Shopify/checkout-sheet-kit-react-native#64]
Hey guys 👋🏼 

I have implemented your SDK and may contribute to it at some point. I have noticed that the SDK displays the checkout experience through a WebView. Which is fine but not ideal from a user perspective.

While I appreciate your efforts in customizing the WebView, it still does not have the same effect as a fully native SDK. I am curious about the long-term plan for the SDK and would like to understand Shopify's strategy behind it.

**Comment by markmur** [comment]
Hey @anthlasserre,

We have plans to improve the experience of the webview, to make it feel more native and idiomatic but have no plans right now to make the library entirely native. This may change in future.

We will happily accept contributions 👍 

Thanks
