### ISSUE TITLE
Cart buyer identity is not pre-filled in the checkout

### ISSUE THREAD

**Issue by mk-nickyang** [Shopify/checkout-sheet-kit-react-native#77]
**Describe the bug**

I have `email` buyer identity data in Cart, 
```
"buyerIdentity": {
    "countryCode": "AU",
    "email": "nickyang0501@gmail.com",
    "phone": null,
    "customer": null
}
```
when I call `shopifyCheckout.present(checkoutUrl)`, email field is still empty.

I'm using the [`cart` query](https://shopify.dev/docs/api/storefront/2024-01/queries/cart) in Storefront API to get the `checkoutUrl` btw.

**To Reproduce**

1. Create a cart with `buyerIdentity` data
2. Call `shopifyCheckout.present(checkoutUrl)`
3. No `buyerIdentity` data is pre-filled

**Expected behavior**

`buyerIdentity` data in Cart should be pre-filled in Checkout

**Screenshots/Videos/Log output**

- React Native using `@shopify/checkout-sheet-kit` (email is not pre-filled)

https://github.com/Shopify/checkout-sheet-kit-react-native/assets/29244509/6e2c13bf-eb90-4355-a3b4-0c69875e67bf

- Same `checkoutUrl` in Web (email is pre-filled)

https://github.com/Shopify/checkout-sheet-kit-react-native/assets/29244509/6264ca9c-054f-4469-8393-c41732cac2d5

**Versions**

 - `@shopify/checkout-sheet-kit` version `2.0.0`
 - Device: iPhone 15 Pro Max (SIM)
 - OS: iOS 17.4

**Shop domain**

https://apawfectplace.com.au/

**Additional context**

Appreciate your time on this issue, let me know if there is anything else you need. Amazing work on this package!

**Comment by navxchahal** [comment]
Facing the same issue, the address and user cannot be prefilled on the checkout screen even after updating the buyerIdentity every time. Kindly update ASAP.

**Comment by koulomesh** [comment]
@markmur Any update on this issue? I tried after implementing multipass also. In the first load, the webview loads with the user being logged in. But when we load the webview, the second time, it asks for login.

**Comment by markmur** [comment]
Hi @koulomesh, would you mind creating another issue outlining how you're creating checkout URL via the storefront API?

This issue is not related to multipass.

**Comment by MoeMamdouh** [comment]
I'm also facing the same issue, Any updates?

**Comment by c-bahar** [comment]
Same issue

**Comment by markmur** [comment]
A fix for this has been rolled out. Apologies for the delay. 

Please report back if you continue to encounter this issue.
