### ISSUE TITLE
Requesting a repository for Flutter.

### ISSUE THREAD

**Issue by tgloc** [Shopify/checkout-sheet-kit-react-native#95]
Hi,

I'm a Flutter developer with four years of experience, currently using Flutter to build an ecommerce mobile application with Shopify. I would like to contribute to this Flutter library. What steps should I take?

Should I share my repository that integrates completely with the iOS and Android SDK, or should I wait for you to create a new Flutter repository to which I can start submitting pull requests?

Looking forward to your response.
Loc.

**Comment by Lennart-Franck** [comment]
Hey @tgloc,

Would it be possible that you share your repository? I think the Flutter community and I would love to see what you already built! 

Thank you :)

**Comment by filipzalewski97** [comment]
> Hi,
> 
> I'm a Flutter developer with four years of experience, currently using Flutter to build an ecommerce mobile application with Shopify. I would like to contribute to this Flutter library. What steps should I take?
> 
> Should I share my repository that integrates completely with the iOS and Android SDK, or should I wait for you to create a new Flutter repository to which I can start submitting pull requests?
> 
> Looking forward to your response. Loc.

Hi, if you could share this repository I would be super thankful.

**Comment by windmillcode0** [comment]
Greetings we are an organization that uses flutter in our application and would like to do so using shopify solutions as well

**Comment by ipqtr** [comment]
Would be great to have one.
