### ISSUE TITLE
Pixel event "checkout_completed" missing for iOS

### ISSUE THREAD

**Issue by BARK-AHAAS** [Shopify/checkout-sheet-kit-react-native#96]
### What area is the issue related to?

Checkout Sheet Kit

### What platform does the issue affect?

iOS

### What version of `@shopify/checkout-sheet-kit` are you using?

3.0.0

### Steps to Reproduce

We are using the checkout sheet for out RN app and leveraging the `pixel` event listener to send events to Amplitude for proper reporting and funnel tracking.  When checking out on an Android device i get the following log of event names (and additional screen pathname for page_viewed events):
```
 LOG  Pixel event "page_viewed"
 LOG  event.context?.window?.location?.pathname /checkouts/cn/Z2NwLXVzLWNlbnRyYWwxOjAxSjBLSjFFWDQxRVdTWkNQWkQ4R0dEOEJW
 LOG  Pixel event "checkout_started"
 LOG  Pixel event "checkout_shipping_info_submitted"
 LOG  Pixel event "checkout_shipping_info_submitted"
 LOG  Pixel event "page_viewed"
 LOG  event.context?.window?.location?.pathname /checkouts/cn/Z2NwLXVzLWNlbnRyYWwxOjAxSjBLSjFFWDQxRVdTWkNQWkQ4R0dEOEJW/processing
 LOG  Pixel event "payment_info_submitted"
 LOG  Pixel event "page_viewed"
 LOG  event.context?.window?.location?.pathname /checkouts/cn/Z2NwLXVzLWNlbnRyYWwxOjAxSjBLSjFFWDQxRVdTWkNQWkQ4R0dEOEJW/processing
 LOG  Pixel event "checkout_completed"
```
When doing the same steps on an iOS device i see the following corresponding logs:
```
 LOG  Pixel event "page_viewed"
 LOG  event.context?.window?.location?.pathname /checkouts/cn/Z2NwLXVzLWVhc3QxOjAxSjBLSko3R1NCTVRaUUoyRFRaR0dCOFZS
 LOG  Pixel event "checkout_started"
 LOG  Pixel event "checkout_shipping_info_submitted"
 LOG  Pixel event "page_viewed"
 LOG  event.context?.window?.location?.pathname /checkouts/cn/Z2NwLXVzLWVhc3QxOjAxSjBLSko3R1NCTVRaUUoyRFRaR0dCOFZS/processing
 LOG  Pixel event "payment_info_submitted"
```

As you can see the events stop after `payment_info_submitted` and there is no `checkout_completed` event fired (as well as a `page_viewed` event.

The steps followed are
1. Log in as a user to get their Multipass 
2. Use that multipass to authenticate the checkout url
3. enter checkout as an authenticated user
4. enter payment information
5. click Pay to complete checkout 

### Expected Behavior

The pixel events are the same between iOS and Android

### Actual Behavior

 there is no `checkout_completed` event fired (as well as a `page_viewed` event on iOS

### Storefront domain

 bark-food.myshopify.com

**Comment by markmur** [comment]
This has been fixed in [@shopify/checkout-sheet-kit@3.0.1](https://github.com/Shopify/checkout-sheet-kit-react-native/releases/3.0.1)
